# ==================================
# Application Abstract Configuration
# ==================================
# Spring
spring:
  # Config
  config:
    use-legacy-processing: true
  # Main
  main:
    allow-bean-definition-overriding: true
  # Profile
  profiles:
    active: @spring.profiles.active@
  # Jackson
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: GMT+3
  # JPA
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: MYSQL
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate.use_outer_join: true
# Server
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
