# ===========================================
# Development Profile DataSource Configuration
# ===========================================

# Spring
spring:
  # Profile
  profiles: dev
  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/messenger?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  # JPA
  jpa:
    show-sql: false
#Logging
#logging:
#  file:
#    name: